main: main.Main
name: Aurabot-Report
description: Reporting plugin, with aura bot.
version: 1.0
commands:
  report:
    description: Report a player.
    usage: /report <player> <reason>
  clearreports:
    description: Clears the reports for a player
    usage: /clearreports <player>
  reports:
    description: Gets the reports of a player
    usage: /getreports <player>
  aurabot:
    description: Summons and aura bot to gather intel on a player
    usage: /aurabot <player>
permissions:
  
  aurabot.*:
    description: Gives access to all aurabot commands, should only be given to administators
    children:
      aurabot.summon: true
      aurabot.recievenotis: true
      aurabot.managethreshold: true

  aurabot.summon:
    description: Allows the player to summon an aurabot to check on another player
    default: op
  aurabot.recievenotis:
    description: Allows the player to recieve notifications on players that have broken the aurabot threshold
    default: op
  aurabot.managethreshold:
    description: Allows the player to change the threshold of the aurabot via /aurabot threshold <int>
    default: op

  report.default:
    description: The default permission a player should get
    children:
      report.send: true
      report.clearreports: false
      report.recievenotis: false
      report.getrepots: false
  report.*:
    description: Gives access to all report commands, should only be given to administators
    children:
      report.send: true
      report.clearreports: true
      report.recievenotis: true
      report.getreports: true
  report.send:
    description: Allows the player to report
    default: true
  report.clearreports:
    description: Allows the player to clear the reports for a user
    default: op
  report.getreports:
    description: Allows the player to recieve the reports of a player.
    default: op
  report.recievenotis:
    description: Gives the player a notification when a player is reported
    default: op

  